version: '3.3'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - appseed-app
  database:
    container_name: db
    image: postgres:13.3
    restart: always
    ports:
      - "5444:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ./pg-data:/var/lib/postgresql/data/
      - type: tmpfs
        target: /dev/shm
    networks:
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
